project: mss-boot
service: task
ports:
  - port: 9090
    targetPort: 9090
    name: grpc
metrics:
  scrape: true
  port: 5000
  path: /metrics
hpa: false
config:
  - name: mss-boot-task-config
    path: /app/cfg
deploy:
  stage:
    alpha:
      cluster: matrix-devops
      namespace: alpha
      autoSync: true
    beta:
      cluster: matrix-devops
      namespace: beta
    prod:
      cluster: matrix-devops
      namespace: prod