server:
  addr: :8080
#health:
#  addr: :4000
#metrics:
#  addr: :5000
logger:
  # 日志类型 default: go-admin-core构建的默认日志插件, zap: zap插件
  type: default
  # 日志存放路径，关闭控制台日志后，日志文件存放位置
  # path: temp/logs
  # 日志输出，file：文件，default：命令行，其他：命令行
  stdout: default #控制台日志，启用后，不输出到文件
  # 日志等级, trace, debug, info, warn, error, fatal
  level: trace
  # 日志格式 json json格式
  formatter: default
database:
  url: ''
  name: mss_boot_admin
  timeout: 10s
# 修改为部署的oauth2服务的配置
oauth2:
  issuer: '222222'
  clientID: mss-boot
  clientSecret: '22222222'
  redirectURL: http://localhost:8080/admin/callback/dexidp
  scopes:
    - openid
    - groups
    - offline_access