project: mss-boot
service: oos-gateway
ports:
  - port: 8080
    targetPort: 8080
    name: http
metrics:
  scrape: true
  port: 5000
  path: /metrics
hpa: false
config:
  - name: mss-boot-oos-gateway-config
    path: /app/cfg