project: mss-boot
service: oos-gateway
ports:
  - port: 8080
    targetPort: 8080
    name: http
metrics:
  scrape: true
  port: 5000
  path: /metrics
hpa: false
config:
  - name: mss-boot-oos-gateway-config
    path: /app/cfg
deploy:
  image: mssbootio/oos-gateway
  stage:
    alpha:
      cluster: matrix-devops
      namespace: alpha
      autoSync: true
    beta:
      cluster: matrix-devops
      namespace: beta
    prod:
      cluster: matrix-devops
      namespace: prod