app: mss-boot
service: admin
ports:
  - port: 8080
    targetPort: 8080
    name: http
metrics:
  scrape: true
  port: 5000
  path: /metrics
hpa: false
configData:
  name: mss-boot-admin-config
  path: /app/cfg
