definitions:
  form.KV:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  form.MenuCreateReq:
    properties:
      access:
        description: 权限
        type: string
      component:
        description: 组件
        type: string
      icon:
        description: icon
        type: string
      layout:
        description: Layout
        type: boolean
      name:
        description: 名称
        type: string
      parentKeys:
        description: 父菜单
        items:
          type: string
        type: array
      path:
        description: 路径
        type: string
      redirect:
        description: 重定向
        type: string
      status:
        description: 状态
        type: integer
      tenantID:
        description: 租户id
        type: string
    required:
    - access
    - name
    - path
    - tenantID
    type: object
  form.MenuGetResp:
    properties:
      access:
        description: 权限
        type: string
      component:
        description: 组件
        type: string
      createdAt:
        description: 创建时间
        type: string
      icon:
        description: icon
        type: string
      id:
        description: id
        type: string
      layout:
        description: Layout
        type: boolean
      name:
        description: 名称
        type: string
      parentKeys:
        description: <no value>
        items:
          type: string
        type: array
      path:
        description: 路径
        type: string
      redirect:
        description: 重定向
        type: string
      status:
        description: 状态
        type: integer
      tenantID:
        description: 租户id
        type: string
      updatedAt:
        description: 更新时间
        type: string
    type: object
  form.MenuListItem:
    properties:
      access:
        description: 权限
        type: string
      component:
        description: 组件
        type: string
      icon:
        description: icon
        type: string
      id:
        description: id
        type: string
      layout:
        description: Layout
        type: boolean
      name:
        description: 名称
        type: string
      parentKeys:
        description: <no value>
        items:
          type: string
        type: array
      path:
        description: 路径
        type: string
      redirect:
        description: 重定向
        type: string
      routes:
        items:
          $ref: '#/definitions/form.MenuListItem'
        type: array
      status:
        description: 状态
        type: integer
      tenantID:
        description: 租户id
        type: string
    type: object
  form.MenuUpdateReq:
    properties:
      access:
        description: 权限
        type: string
      component:
        description: 组件
        type: string
      icon:
        description: icon
        type: string
      layout:
        description: Layout
        type: boolean
      name:
        description: 名称
        type: string
      parentKeys:
        description: 父菜单
        items:
          type: string
        type: array
      path:
        description: 路径
        type: string
      redirect:
        description: 重定向
        type: string
      status:
        description: 状态
        type: integer
      tenantID:
        description: 租户id
        type: string
    required:
    - access
    - name
    - path
    - tenantID
    type: object
  form.SettingsUpdateReq:
    properties:
      settings:
        items:
          $ref: '#/definitions/form.KV'
        type: array
    type: object
  form.TenantCallbackResp:
    properties:
      accessToken:
        description: |-
          AccessToken is the token that authorizes and authenticates
          the requests.
        type: string
      expiry:
        description: |-
          Expiry is the optional expiration time of the access token.

          If zero, TokenSource implementations will reuse the same
          token forever and RefreshToken or equivalent
          mechanisms for that TokenSource will not be used.
        type: string
      refreshToken:
        description: |-
          RefreshToken is a token that's used by the application
          (as opposed to the user) to refresh the access token
          if it expires.
        type: string
      tokenType:
        description: |-
          TokenType is the type of token.
          The Type method returns either this or "Bearer", the default.
        type: string
    type: object
  form.TenantClientResp:
    properties:
      appName:
        type: string
      authCodeURL:
        type: string
      clientId:
        type: string
      organizationName:
        type: string
      serverUrl:
        type: string
    type: object
  form.TenantCreateReq:
    properties:
      contact:
        description: 联系方式
        type: string
      description:
        description: 描述
        type: string
      domains:
        description: 域名
        items:
          type: string
        type: array
      email:
        description: 邮箱
        type: string
      expiredAt:
        description: 有效期
        type: string
      name:
        description: 名称
        type: string
      status:
        description: 状态
        type: integer
      system:
        description: 系统管理
        type: boolean
    required:
    - expiredAt
    - name
    type: object
  form.TenantGetResp:
    properties:
      contact:
        description: 联系方式
        type: string
      createdAt:
        description: 创建时间
        type: string
      description:
        description: 描述
        type: string
      domains:
        description: 域名
        items:
          type: string
        type: array
      expiredAt:
        description: 有效期
        type: string
      name:
        description: 名称
        type: string
      status:
        description: 状态
        type: integer
      system:
        description: 系统管理
        type: boolean
      updatedAt:
        description: 更新时间
        type: string
    required:
    - expiredAt
    type: object
  form.TenantListItem:
    properties:
      contact:
        description: 联系方式
        type: string
      createdAt:
        description: 创建时间
        type: string
      description:
        description: 描述
        type: string
      domains:
        description: 域名
        items:
          type: string
        type: array
      expiredAt:
        description: 有效期
        type: string
      id:
        description: id
        type: string
      name:
        description: 名称
        type: string
      status:
        description: 状态
        type: integer
      system:
        description: 系统管理
        type: boolean
      updatedAt:
        description: 更新时间
        type: string
    required:
    - expiredAt
    type: object
  form.TenantUpdateReq:
    properties:
      contact:
        description: 联系方式
        type: string
      description:
        description: 描述
        type: string
      domains:
        description: 域名
        items:
          type: string
        type: array
      email:
        description: 邮箱
        type: string
      expiredAt:
        description: 有效期
        type: string
      name:
        description: 名称
        type: string
    required:
    - expiredAt
    type: object
  middlewares.User:
    properties:
      at_hash:
        type: string
      aud:
        type: string
      email:
        type: string
      email_verified:
        type: boolean
      exp:
        type: integer
      groups:
        items:
          type: string
        type: array
      iat:
        type: integer
      iss:
        type: string
      name:
        type: string
      sub:
        type: string
    type: object
  response.Page:
    properties:
      current:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  response.Response:
    properties:
      errorCode:
        type: string
      errorMessage:
        type: string
      host:
        type: string
      showType:
        type: integer
      success:
        type: boolean
      traceId:
        type: string
    type: object
info:
  contact: {}
  description: admin接口文档
  title: admin API
  version: 0.0.1
paths:
  /admin/api/v1/callback:
    get:
      consumes:
      - application/json
      description: 获取access_token
      parameters:
      - description: code
        in: query
        name: code
        type: string
      - description: state
        in: query
        name: state
        type: string
      - description: error
        in: query
        name: error
        type: string
      - description: error_description
        in: query
        name: error_description
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/form.TenantCallbackResp'
              type: object
      summary: 获取access_token
      tags:
      - admin
  /admin/api/v1/client:
    get:
      consumes:
      - application/json
      description: 获取client配置
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/form.TenantClientResp'
              type: object
      security:
      - Bearer: []
      summary: 获取client配置
      tags:
      - admin
  /admin/api/v1/current-user:
    get:
      consumes:
      - application/json
      description: 获取当前用户
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/middlewares.User'
              type: object
      security:
      - Bearer: []
      summary: 获取当前用户
      tags:
      - admin
  /admin/api/v1/menu:
    get:
      consumes:
      - application/json
      description: 列表menu
      parameters:
      - description: 租户名称
        in: query
        name: name
        type: string
      - description: 当前页
        in: query
        name: page
        type: string
      - description: 每页容量
        in: query
        name: pageSize
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Page'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/form.MenuListItem'
                  type: array
              type: object
      security:
      - Bearer: []
      summary: 列表menu
      tags:
      - menu
    post:
      consumes:
      - application/json
      description: 创建menu
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/form.MenuCreateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Bearer: []
      summary: 创建menu
      tags:
      - menu
  /admin/api/v1/menu/{id}:
    delete:
      consumes:
      - application/json
      description: 删除menu
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Bearer: []
      summary: 删除menu
      tags:
      - menu
    get:
      consumes:
      - application/json
      description: 获取menu
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/form.MenuGetResp'
              type: object
      security:
      - Bearer: []
      summary: 获取menu
      tags:
      - menu
    put:
      consumes:
      - application/json
      description: 更新menu
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/form.MenuUpdateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Bearer: []
      summary: 更新menu
      tags:
      - menu
  /admin/api/v1/settings:
    get:
      consumes:
      - application/json
      description: 获取settings
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/form.KV'
                  type: array
              type: object
      security:
      - Bearer: []
      summary: 获取settings
      tags:
      - settings
    put:
      consumes:
      - application/json
      description: 更新settings
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/form.SettingsUpdateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Bearer: []
      summary: 更新settings
      tags:
      - settings
  /admin/api/v1/tenant:
    get:
      consumes:
      - application/json
      description: 列表tenant
      parameters:
      - description: 租户名称
        in: query
        name: name
        type: string
      - description: 当前页
        in: query
        name: page
        type: string
      - description: 每页容量
        in: query
        name: pageSize
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Page'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/form.TenantListItem'
                  type: array
              type: object
      security:
      - Bearer: []
      summary: 列表tenant
      tags:
      - admin
    post:
      consumes:
      - application/json
      description: 创建tenant
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/form.TenantCreateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Bearer: []
      summary: 创建tenant
      tags:
      - admin
  /admin/api/v1/tenant/{id}:
    delete:
      consumes:
      - application/json
      description: 删除tenant
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Bearer: []
      summary: 删除tenant
      tags:
      - admin
    get:
      consumes:
      - application/json
      description: 获取tenant
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/form.TenantGetResp'
              type: object
      security:
      - Bearer: []
      summary: 获取tenant
      tags:
      - admin
    put:
      consumes:
      - application/json
      description: 更新tenant
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/form.TenantUpdateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Bearer: []
      summary: 更新tenant
      tags:
      - admin
  /admin/pi/v1/refresh-token:
    get:
      consumes:
      - application/json
      description: 获取accessToken
      parameters:
      - description: refreshToken
        in: query
        name: refreshToken
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/form.TenantCallbackResp'
              type: object
      security:
      - Bearer: []
      summary: 获取accessToken
      tags:
      - admin
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
