definitions:
  auth.Claims:
    properties:
      accessToken:
        type: string
      address:
        items:
          type: string
        type: array
      affiliation:
        type: string
      aud:
        description: the `aud` (Audience) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3
        items:
          type: string
        type: array
      avatar:
        type: string
      bio:
        type: string
      birthday:
        type: string
      createdIp:
        type: string
      createdTime:
        type: string
      dingtalk:
        type: string
      displayName:
        type: string
      education:
        type: string
      email:
        type: string
      exp:
        $ref: '#/definitions/jwt.NumericDate'
        description: the `exp` (Expiration Time) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4
      facebook:
        type: string
      gender:
        type: string
      gitee:
        type: string
      github:
        type: string
      gitlab:
        type: string
      google:
        type: string
      hash:
        type: string
      homepage:
        type: string
      iat:
        $ref: '#/definitions/jwt.NumericDate'
        description: the `iat` (Issued At) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6
      id:
        type: string
      idCard:
        type: string
      idCardType:
        type: string
      isAdmin:
        type: boolean
      isDefaultAvatar:
        type: boolean
      isDeleted:
        type: boolean
      isForbidden:
        type: boolean
      isGlobalAdmin:
        type: boolean
      isOnline:
        type: boolean
      iss:
        description: the `iss` (Issuer) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.1
        type: string
      jti:
        description: the `jti` (JWT ID) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.7
        type: string
      karma:
        type: integer
      language:
        type: string
      lark:
        type: string
      lastSigninIp:
        type: string
      lastSigninTime:
        type: string
      ldap:
        type: string
      linkedin:
        type: string
      location:
        type: string
      name:
        type: string
      nbf:
        $ref: '#/definitions/jwt.NumericDate'
        description: the `nbf` (Not Before) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.5
      owner:
        type: string
      password:
        type: string
      passwordSalt:
        type: string
      permanentAvatar:
        type: string
      phone:
        type: string
      preHash:
        type: string
      properties:
        additionalProperties:
          type: string
        type: object
      qq:
        type: string
      ranking:
        type: integer
      region:
        type: string
      score:
        type: integer
      signupApplication:
        type: string
      sub:
        description: the `sub` (Subject) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.2
        type: string
      tag:
        type: string
      title:
        type: string
      type:
        type: string
      updatedTime:
        type: string
      wechat:
        type: string
      wecom:
        type: string
      weibo:
        type: string
    type: object
  form.TenantCallbackResp:
    properties:
      accessToken:
        description: |-
          AccessToken is the token that authorizes and authenticates
          the requests.
        type: string
      expiry:
        description: |-
          Expiry is the optional expiration time of the access token.

          If zero, TokenSource implementations will reuse the same
          token forever and RefreshToken or equivalent
          mechanisms for that TokenSource will not be used.
        type: string
      refreshToken:
        description: |-
          RefreshToken is a token that's used by the application
          (as opposed to the user) to refresh the access token
          if it expires.
        type: string
      tokenType:
        description: |-
          TokenType is the type of token.
          The Type method returns either this or "Bearer", the default.
        type: string
    type: object
  form.TenantClientResp:
    properties:
      appName:
        type: string
      authCodeURL:
        type: string
      clientId:
        type: string
      organizationName:
        type: string
      serverUrl:
        type: string
    type: object
  jwt.NumericDate:
    properties:
      time.Time:
        type: string
    type: object
  response.Response:
    properties:
      errorCode:
        type: string
      errorMessage:
        type: string
      host:
        type: string
      showType:
        type: integer
      success:
        type: boolean
      traceId:
        type: string
    type: object
info:
  contact: {}
  description: admin接口文档
  title: admin API
  version: 0.0.1
paths:
  /admin/api/v1/callback:
    get:
      consumes:
      - application/json
      description: 获取access_token
      parameters:
      - description: code
        in: query
        name: code
        type: string
      - description: state
        in: query
        name: state
        type: string
      - description: error
        in: query
        name: error
        type: string
      - description: error_description
        in: query
        name: error_description
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/form.TenantCallbackResp'
              type: object
      security:
      - Bearer: []
      summary: 获取access_token
      tags:
      - admin
  /admin/api/v1/client:
    get:
      consumes:
      - application/json
      description: 获取client配置
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/form.TenantClientResp'
              type: object
      security:
      - Bearer: []
      summary: 获取client配置
      tags:
      - admin
  /admin/api/v1/current-user:
    get:
      consumes:
      - application/json
      description: 获取当前用户
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/auth.Claims'
              type: object
      security:
      - Bearer: []
      summary: 获取当前用户
      tags:
      - admin
  /admin/api/v1/refresh-token:
    get:
      consumes:
      - application/json
      description: 获取accessToken
      parameters:
      - description: refreshToken
        in: query
        name: refreshToken
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/form.TenantCallbackResp'
              type: object
      security:
      - Bearer: []
      summary: 获取accessToken
      tags:
      - admin
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
