on:
  workflow_call:
    inputs:
      leaf:
        description: 'leaf names'
        required: true
        default: '[]'
        type: string
      image_tags:
        description: 'image tag'
        required: false
        default: ${{ github.sha }}
        type: string
      config_stage:
        description: 'config stage'
        required: false
        default: 'test'
        type: string
    secrets:
      aws_account:
        required: true
        description: aws account
      aws_region:
        required: true
        description: aws region
      gitops_deploy_key:
        required: true
        description: ''
      dockerhub_token:
        required: true
        description: ''
      dockerhub_username:
        required: true
        description: ''

jobs:
  build:
    name: cicd
    runs-on: self-hosted
    env:
      repo: ${{ github.repository }}
      mark: ${{ github.sha }}
      bucket: matrixlabs-github-runner-artifact
      region: ${{ secrets.aws_region }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.aws_region }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}


      - name: install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Build && Deploy
        run: |
          aws s3 cp s3://matrixlabs-github-runner-artifact/WhiteMatrixTech/workflow-tools-go/v1.0.3/bin/workflow-tools . --quiet
          chmod +x ./workflow-tools
          ./workflow-tools mk --docker-push=true --generate-cdk8s=true
        env:
          leaf: ${{ inputs.leaf }}
          cmd: cp -r ../../bin ./ && make generate && make test && make build
          docker_organize: mssbootio
          docker_tags: ${{ inputs.image_tags }}
          ci: true
          config_stage: ${{ inputs.config_stage }}

      - name: Push K8S Yaml
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.gitops_deploy_key }}
          publish_dir: ./dist
          keep_files: true
          publish_branch: main
          destination_dir: mss-boot-monorepo
          external_repository: mss-boot-io/mss-boot-gitops