on:
  workflow_call:
    inputs:
      leaf:
        description: 'leaf names'
        required: true
        default: '[]'
        type: string
      image_tags:
        description: 'image tag'
        required: false
        default: ${{ github.sha }}
        type: string
      stage:
        description: 'stage'
        required: false
        default: 'alpha'
        type: string
      pr_number:
        description: 'pr number'
        required: false
        default: ''
        type: string
      downloadArtifact:
        description: 'download artifact'
        required: false
        default: true
        type: boolean
    secrets:
      aws_account:
        required: true
        description: aws account
      aws_region:
        required: true
        description: aws region
      gitops_deploy_key:
        required: true
        description: ''
      dockerhub_token:
        required: true
        description: ''
      dockerhub_username:
        required: true
        description: ''

jobs:
  build:
    name: cicd
    runs-on: ubuntu-latest
    env:
      repo: ${{ github.repository }}
      mark: ${{ github.sha }}
      bucket: matrixlabs-github-runner-artifact
      region: ${{ secrets.aws_region }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        if: ${{ inputs.downloadArtifact }}
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: artifact

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}


      - name: install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Add Artifact Dir
        run: mkdir dist

      - name: Build && Deploy
        run: |
          wget https://github.com/mss-boot-io/workflow-tools-go/releases/download/v0.0.1/workflow-tools
          chmod +x ./workflow-tools
          ./workflow-tools mk --docker-push=true --generate-cdk8s=true --store-provider=local
        env:
          leaf: ${{ inputs.leaf }}
          cmd: cp -r ../../bin ./ && go mod tidy && make generate && make test && make build
          docker_organize: mssbootio
          docker_tags: ${{ inputs.image_tags }}
          ci: true
          config_stage: ${{ inputs.stage }}
          coverage_standard: 60
          repo_path: ${{ github.repository }}
          pr_number: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          error_block: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ inputs.stage }}-${{ github.sha}}
          path: dist
          retention-days: 3

  deployment:
    name: deployment
    runs-on: ubuntu-latest
    environment: ${{ inputs.stage }}
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-${{ inputs.stage }}-${{ github.sha}}
          path: dist

      - name: Push K8S Yaml
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.gitops_deploy_key }}
          publish_dir: ./dist
          keep_files: true
          publish_branch: main
          destination_dir: mss-boot-monorepo
          external_repository: mss-boot-io/mss-boot-gitops