name: Operate Build

on:
  workflow_dispatch:
    inputs:
      service:
        description: "services(json array service name and service type(service or lambda))"
        default: '[{"name": "admin", "type": "service", "language": "golang"}]'
        required: true
      config_stage:
        description: "config stage"
        default: "test"
        required: true
      stage:
        description: "stage"
        default: "beta"
        required: true

jobs:
  cicd:
    uses: mss-boot-io/mss-boot-monorepo/.github/workflows/cicd.yml@main
    if: ${{ github.event.inputs.service != '' && github.event_name == 'workflow_dispatch' }}
    with:
      leaf: ${{ github.event.inputs.service }}
      image_tags: ${{ github.sha }}
      stage: ${{ github.event.inputs.stage }}
      config_stage: ${{ github.event.inputs.config_stage }}
    secrets:
      aws_region: ${{ secrets.aws_region }}
      aws_account: ${{ secrets.aws_account }}
      gitops_deploy_key: ${{ secrets.gitops_deploy_key }}
      dockerhub_username: ${{ secrets.dockerhub_username }}
      dockerhub_token: ${{ secrets.dockerhub_token }}