name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
  cicd:
    uses: mss-boot-io/mss-boot-monorepo/.github/workflows/cicd.yml@main
    needs: triage
    with:
      leaf: ${{ needs.leaf.outputs.leaf }}
      image_tags: ${{ github.sha }}
      stage: beta
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      aws_region: ${{ secrets.aws_region }}
      aws_account: ${{ secrets.aws_account }}
      gitops_deploy_key: ${{ secrets.gitops_deploy_key }}
      dockerhub_username: ${{ secrets.dockerhub_username }}
      dockerhub_token: ${{ secrets.dockerhub_token }}